/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class main_nativefft_AudioFFT */

#ifndef _Included_main_nativefft_AudioFFT
#define _Included_main_nativefft_AudioFFT
#ifdef __cplusplus
extern "C" {
#endif
#undef main_nativefft_AudioFFT_time_samples
#define main_nativefft_AudioFFT_time_samples 128L
/*
 * Class:     main_nativefft_AudioFFT
 * Method:    performAudioTransform
 * Signature: ([F[F[F)[F
 */
JNIEXPORT jfloatArray JNICALL Java_main_nativefft_AudioFFT_performAudioTransform
  (JNIEnv *, jobject, jfloatArray, jfloatArray, jfloatArray);

#ifdef __cplusplus
}
#endif
#endif
