/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class main_nativefft_IRFTransform */

#ifndef _Included_main_nativefft_IRFTransform
#define _Included_main_nativefft_IRFTransform
#ifdef __cplusplus
extern "C" {
#endif
#undef main_nativefft_IRFTransform_time_samples
#define main_nativefft_IRFTransform_time_samples 128L
/*
 * Class:     main_nativefft_IRFTransform
 * Method:    FFT
 * Signature: ([F)[F
 */
JNIEXPORT jfloatArray JNICALL Java_main_nativefft_IRFTransform_FFT
  (JNIEnv *, jobject, jfloatArray);

#ifdef __cplusplus
}
#endif
#endif
