sources = 	hc2hc-generic.c \
	hc2hc.c \
	problem2.c \
	indirect.c \
	rank0-rdft2.c \
	vrank-geq1-rdft2.c \
	nop2.c \
	rdft2-rdft.c \
	direct2.c \
	rdft2-strides.c \
	solve2.c \
	vrank-geq1.c \
	ct-hc2c.c \
	problem.c \
	rdft2-inplace-strides.c \
	dft-r2hc.c \
	plan.c \
	nop.c \
	buffered.c \
	kr2r.c \
	rdft2-tensor-max-index.c \
	buffered2.c \
	direct-r2c.c \
	dht-rader.c \
	plan2.c \
	conf.c \
	rank0.c \
	vrank3-transpose.c \
	khc2c.c \
	generic.c \
	dht-r2hc.c \
	hc2hc-direct.c \
	rank-geq2.c \
	ct-hc2c-direct.c \
	kr2c.c \
	direct-r2r.c \
	rdft-dht.c \
	rank-geq2-rdft2.c \
	solve.c \
	khc2hc.c \

LOCAL_SRC_FILES += $(sources:%=rdft/%)