sources = 	plan-dft-3d.c \
	mktensor-rowmajor.c \
	plan-guru-split-dft-r2c.c \
	plan-r2r.c \
	forget-wisdom.c \
	configure.c \
	plan-guru64-split-dft-r2c.c \
	plan-dft-c2r-2d.c \
	execute-dft-c2r.c \
	flops.c \
	plan-guru-dft.c \
	plan-guru-split-dft-c2r.c \
	plan-many-dft.c \
	plan-guru-dft-c2r.c \
	plan-r2r-2d.c \
	plan-dft-1d.c \
	plan-many-dft-r2c.c \
	rdft2-pad.c \
	execute-split-dft-c2r.c \
	execute-dft.c \
	execute-split-dft-r2c.c \
	plan-dft-r2c-2d.c \
	import-wisdom-from-string.c \
	plan-guru-split-dft.c \
	plan-many-r2r.c \
	plan-dft-c2r-3d.c \
	plan-dft-r2c.c \
	plan-guru64-r2r.c \
	malloc.c \
	plan-dft-2d.c \
	execute-r2r.c \
	plan-dft-r2c-1d.c \
	plan-guru64-dft-r2c.c \
	import-system-wisdom.c \
	version.c \
	plan-many-dft-c2r.c \
	plan-r2r-1d.c \
	print-plan.c \
	import-wisdom.c \
	execute-dft-r2c.c \
	plan-dft-c2r.c \
	apiplan.c \
	execute.c \
	export-wisdom-to-file.c \
	the-planner.c \
	plan-dft-c2r-1d.c \
	execute-split-dft.c \
	mapflags.c \
	plan-dft.c \
	plan-guru64-split-dft.c \
	mktensor-iodims.c \
	import-wisdom-from-file.c \
	mkprinter-file.c \
	plan-dft-r2c-3d.c \
	export-wisdom-to-string.c \
	plan-r2r-3d.c \
	plan-guru64-split-dft-c2r.c \
	plan-guru64-dft-c2r.c \
	plan-guru-r2r.c \
	f77api.c \
	plan-guru64-dft.c \
	mktensor-iodims64.c \
	map-r2r-kind.c \
	plan-guru-dft-r2c.c \
	export-wisdom.c 

LOCAL_SRC_FILES += $(sources:%=api/%)