/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_audioplayback_NativeConvolve */

#ifndef _Included_com_example_audioplayback_NativeConvolve
#define _Included_com_example_audioplayback_NativeConvolve
#ifdef __cplusplus
extern "C" {
#endif
#undef com_example_audioplayback_NativeConvolve_time_samples
#define com_example_audioplayback_NativeConvolve_time_samples 128L
/*
 * Class:     com_example_audioplayback_NativeConvolve
 * Method:    convolve
 * Signature: ([F[F[F)[F
 */
JNIEXPORT jfloatArray JNICALL Java_com_example_audioplayback_NativeConvolve_convolve
  (JNIEnv *, jobject, jfloatArray, jfloatArray, jfloatArray);

#ifdef __cplusplus
}
#endif
#endif
